---
name: test
on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.14'
          - '5.24'
          - latest
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: perl-version
        run: perl -V

      - uses: actions/cache@v1
        id: cache
        with:
          path: /user/local/lib/perl5
          key: ${{ runner.os }}-perlib-${{ matrix.perl-version }}-${{ hashFiles('cpanfile') }}
          restore-keys: ${{ runner.os }}-perlib-${{ matrix.perl-version }}-

      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cpanm --installdeps .
          cpanm -n Devel::Cover
          cpanm -n Devel::Cover::Report::Coveralls

      - name: test
        run: prove -Ilib -r
        env:
          HARNESS_PERL_SWITCHES: -MDevel::Cover

      - name: coverage
        run: |
          echo 'repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}' > .coveralls.yml
          cover -test -report coveralls
