---
name: test
on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.14'
          - '5.24'
          - latest
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: perl-version
        run: perl -V

      - uses: actions/cache@v1
        id: cache
        with:
          path: local
          key: ${{ runner.os }}-carton-${{ matrix.perl-version }}-${{ hashFiles('cpanfile') }}
          restore-keys: ${{ runner.os }}-carton-${{ matrix.perl-version }}-

      - name: install deps
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cpanm -n Carton
          carton install
          cpanm -n Devel::Cover::Report::Coveralls

      - name: test
        run: |
          carton exec prove -Ilib -r
